image: maven:3-jdk-8

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B verify sonar:sonar -Dvcs.name=bb -Dsonar.login=$SONAR_LOGIN # -B batch mode makes Maven less verbose
